//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public int BanId { get; set; }
        public string Nickname { get; set; }
        public System.TimeSpan BanTime { get; set; }
        public string BanType { get; set; }
    
        public virtual User User { get; set; }
    }
}
