//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeck
    {
        public int UserDeckId { get; set; }
        public string Nickname { get; set; }
        public int DeckId { get; set; }
    
        public virtual Deck Deck { get; set; }
        public virtual User User { get; set; }
    }
}
