//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string nickName { get; set; }
        public string mail { get; set; }
        public int imageId { get; set; }
        public Nullable<int> userSessionFk { get; set; }
    
        public virtual UserSession UserSession { get; set; }
    }
}
