//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriend
    {
        public int UserFriendId { get; set; }
        public string Nickname1 { get; set; }
        public string Nickname2 { get; set; }
        public int FriendStatusId { get; set; }
    
        public virtual FriendStatus FriendStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
