//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AstralisDBEntities : DbContext
    {
        public AstralisDBEntities()
            : base("name=AstralisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ban> Ban { get; set; }
        public virtual DbSet<Deck> Deck { get; set; }
        public virtual DbSet<FriendStatus> FriendStatus { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Plays> Plays { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserDeck> UserDeck { get; set; }
        public virtual DbSet<UserFriend> UserFriend { get; set; }
        public virtual DbSet<UserSession> UserSession { get; set; }
    }
}
