//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astralis.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Astralis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar código.
        /// </summary>
        public static string btnCopyToClipboard {
            get {
                return ResourceManager.GetString("btnCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREAR PARTIDA.
        /// </summary>
        public static string btnCreateGame {
            get {
                return ResourceManager.GetString("btnCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAZOS.
        /// </summary>
        public static string btnDecks {
            get {
                return ResourceManager.GetString("btnDecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string btnEnglish {
            get {
                return ResourceManager.GetString("btnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALIR.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        public static string btnJoin {
            get {
                return ResourceManager.GetString("btnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unirse como invitado.
        /// </summary>
        public static string btnJoinAsGuest {
            get {
                return ResourceManager.GetString("btnJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIRSE A PARTIDA.
        /// </summary>
        public static string btnJoinGame {
            get {
                return ResourceManager.GetString("btnJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulsar.
        /// </summary>
        public static string btnKickout {
            get {
                return ResourceManager.GetString("btnKickout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLERO.
        /// </summary>
        public static string btnLeaderbord {
            get {
                return ResourceManager.GetString("btnLeaderbord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string btnLogIn {
            get {
                return ResourceManager.GetString("btnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi perfil.
        /// </summary>
        public static string btnMyProfile {
            get {
                return ResourceManager.GetString("btnMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar invitación.
        /// </summary>
        public static string btnSendInvitation {
            get {
                return ResourceManager.GetString("btnSendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string btnSendMessage {
            get {
                return ResourceManager.GetString("btnSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURACIÓN.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string btnSpanish {
            get {
                return ResourceManager.GetString("btnSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo 1.
        /// </summary>
        public static string cbxTeamOne {
            get {
                return ResourceManager.GetString("cbxTeamOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo 2.
        /// </summary>
        public static string cbxTeamTwo {
            get {
                return ResourceManager.GetString("cbxTeamTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código:.
        /// </summary>
        public static string lblCodeInvitation {
            get {
                return ResourceManager.GetString("lblCodeInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar contraseña.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca un correo existente.
        /// </summary>
        public static string lblErrorMail {
            get {
                return ResourceManager.GetString("lblErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no debe incluir espacios.
        /// </summary>
        public static string lblErrorNickname {
            get {
                return ResourceManager.GetString("lblErrorNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuario ya existe.
        /// </summary>
        public static string lblErrorNicknameRepeated {
            get {
                return ResourceManager.GetString("lblErrorNicknameRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es muy debil.
        /// </summary>
        public static string lblErrorPassword {
            get {
                return ResourceManager.GetString("lblErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string lblErrorPasswordsNoMatch {
            get {
                return ResourceManager.GetString("lblErrorPasswordsNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juego abortado, no hay ganadores.
        /// </summary>
        public static string lblGameAborted {
            get {
                return ResourceManager.GetString("lblGameAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string lblGameCode {
            get {
                return ResourceManager.GetString("lblGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas ganadas.
        /// </summary>
        public static string lblGamesWon {
            get {
                return ResourceManager.GetString("lblGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar amigo.
        /// </summary>
        public static string lblInviteFriend {
            get {
                return ResourceManager.GetString("lblInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitar con codigo.
        /// </summary>
        public static string lblInviteWithCode {
            get {
                return ResourceManager.GetString("lblInviteWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLERO.
        /// </summary>
        public static string lblLeaderboard {
            get {
                return ResourceManager.GetString("lblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sala.
        /// </summary>
        public static string lblLobby {
            get {
                return ResourceManager.GetString("lblLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost :c.
        /// </summary>
        public static string lblLoserTeam {
            get {
                return ResourceManager.GetString("lblLoserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string lblMail {
            get {
                return ResourceManager.GetString("lblMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi perfil.
        /// </summary>
        public static string lblMyProfile {
            get {
                return ResourceManager.GetString("lblMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi apodo.
        /// </summary>
        public static string lblNickname {
            get {
                return ResourceManager.GetString("lblNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si necesitas ayuda pon el cursor aqui.
        /// </summary>
        public static string lblPasswordHelp {
            get {
                return ResourceManager.GetString("lblPasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        public static string lblPlayer {
            get {
                return ResourceManager.GetString("lblPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores Conectados.
        /// </summary>
        public static string lblPlayersConecteds {
            get {
                return ResourceManager.GetString("lblPlayersConecteds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen de perfil.
        /// </summary>
        public static string lblProfileImage {
            get {
                return ResourceManager.GetString("lblProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string lblRegistration {
            get {
                return ResourceManager.GetString("lblRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASTRALIS.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipo: .
        /// </summary>
        public static string lblUserTeam {
            get {
                return ResourceManager.GetString("lblUserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es tu turno.
        /// </summary>
        public static string lblUserTurnFalse {
            get {
                return ResourceManager.GetString("lblUserTurnFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es tu turno.
        /// </summary>
        public static string lblUserTurnTrue {
            get {
                return ResourceManager.GetString("lblUserTurnTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen.
        /// </summary>
        public static string lblVolume {
            get {
                return ResourceManager.GetString("lblVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has ganado!!.
        /// </summary>
        public static string lblWinnerTeam {
            get {
                return ResourceManager.GetString("lblWinnerTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estas baneado, intenta mas tarde..
        /// </summary>
        public static string msgBanned {
            get {
                return ResourceManager.GetString("msgBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al conectarse con el servidor.
        /// </summary>
        public static string msgConnectionError {
            get {
                return ResourceManager.GetString("msgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha sido copiado el texto:.
        /// </summary>
        public static string msgCopyToClipboard {
            get {
                return ResourceManager.GetString("msgCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el lobby.
        /// </summary>
        public static string msgErrorCreateLobby {
            get {
                return ResourceManager.GetString("msgErrorCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigo eliminado exitosamente.
        /// </summary>
        public static string msgFriendRemoved {
            get {
                return ResourceManager.GetString("msgFriendRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de amistad aceptada con éxito.
        /// </summary>
        public static string msgFriendRequestAccepted {
            get {
                return ResourceManager.GetString("msgFriendRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de amistad rechazada con éxito.
        /// </summary>
        public static string msgFriendRequestDeclined {
            get {
                return ResourceManager.GetString("msgFriendRequestDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de amistar enviada con éxito.
        /// </summary>
        public static string msgFriendRequestSuccessful {
            get {
                return ResourceManager.GetString("msgFriendRequestSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El lobby esta lleno o no existe.
        /// </summary>
        public static string msgGameIsFullOrLobbyDoesntExist {
            get {
                return ResourceManager.GetString("msgGameIsFullOrLobbyDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has sido expulsado del lobby..
        /// </summary>
        public static string msgKickedOut {
            get {
                return ResourceManager.GetString("msgKickedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La lobby esta llena o hay un problema con el servidor.
        /// </summary>
        public static string msgLobbyError {
            get {
                return ResourceManager.GetString("msgLobbyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el lobby.
        /// </summary>
        public static string msgNoGameFound {
            get {
                return ResourceManager.GetString("msgNoGameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha perdido la conexión previa.
        /// </summary>
        public static string msgPreviousConnectioLost {
            get {
                return ResourceManager.GetString("msgPreviousConnectioLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo procesar tu solicitud..
        /// </summary>
        public static string msgUnableToAnswer {
            get {
                return ResourceManager.GetString("msgUnableToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo enviar la solicitud de amistad. Verifica que el usuario existe y no haya una solicitud pendiente..
        /// </summary>
        public static string msgUnableToSendFriendRequest {
            get {
                return ResourceManager.GetString("msgUnableToSendFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Registro exitoso!.
        /// </summary>
        public static string msgUserAddedSucceed {
            get {
                return ResourceManager.GetString("msgUserAddedSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingresa un nombre de usuario..
        /// </summary>
        public static string msgUsernameMissing {
            get {
                return ResourceManager.GetString("msgUsernameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no fue encontrado.
        /// </summary>
        public static string msgUserNotFound {
            get {
                return ResourceManager.GetString("msgUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo iniciar sesión debido a que el usuario está en línea.
        /// </summary>
        public static string msgUserOnline {
            get {
                return ResourceManager.GetString("msgUserOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha actualizado correctamen, se reinicará la aplicación.
        /// </summary>
        public static string msgUserUpdated {
            get {
                return ResourceManager.GetString("msgUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASTRALIS.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiado.
        /// </summary>
        public static string titleCopyToClipboard {
            get {
                return ResourceManager.GetString("titleCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string titleError {
            get {
                return ResourceManager.GetString("titleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulsado.
        /// </summary>
        public static string titleKickedOut {
            get {
                return ResourceManager.GetString("titleKickedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string titleMail {
            get {
                return ResourceManager.GetString("titleMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro.
        /// </summary>
        public static string titleNoGameFound {
            get {
                return ResourceManager.GetString("titleNoGameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string titleUserAdded {
            get {
                return ResourceManager.GetString("titleUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa un correo valido.
        /// </summary>
        public static string tpMailHelp {
            get {
                return ResourceManager.GetString("tpMailHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe incluir letras de la A a la Z, numeros y signos como: !@#$%&amp;.
        /// </summary>
        public static string tpNicknameHelp {
            get {
                return ResourceManager.GetString("tpNicknameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe tener mas de 2 y menos de 30 caracteres.
        /// </summary>
        public static string tpNicknameLenghtHelp {
            get {
                return ResourceManager.GetString("tpNicknameLenghtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo no puede estar vacío.
        /// </summary>
        public static string txbEmptyFieldError {
            get {
                return ResourceManager.GetString("txbEmptyFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales invalidas, favor de introducir un usuario valido.
        /// </summary>
        public static string txbInvalidFields {
            get {
                return ResourceManager.GetString("txbInvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas de la contraseña:
        ///
        ///Al menos 8 caracteres
        ///Al menos 1 número
        ///Al menos 1 simbolo
        ///Al menos 1 mayuscula.
        /// </summary>
        public static string txbPasswordRules {
            get {
                return ResourceManager.GetString("txbPasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe algo....
        /// </summary>
        public static string txtChat {
            get {
                return ResourceManager.GetString("txtChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo de amigo.
        /// </summary>
        public static string txtFriendMail {
            get {
                return ResourceManager.GetString("txtFriendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escribe un nombre....
        /// </summary>
        public static string txtSearchUser {
            get {
                return ResourceManager.GetString("txtSearchUser", resourceCulture);
            }
        }
    }
}
